[base]
ticket_id = 3 # 致明天

[feishu]
app_id = "cli_xxx"
app_secret = "xxx"
tenant_access_token = "t-xxx"

[table]
table_token = "xxx"
sheet_id = "abcdef"

[header]
need_trim = ["username", "password"]
token = "token"
balance = "balance"